// Hash KWS ensemble aggregator — MCU side.
//
// Mirrors `code/training/hash_ensemble/aggregation.py`. Designed to run on
// either the master node (consuming ESP-NOW packets from peers) or, in
// symmetric mode, on every node (each computes the same aggregate from the
// same inputs).
//
// Memory model:
//   - All buffers are statically sized at compile time; no heap allocation.
//   - One slot per (node_id, last packet) — newer packets overwrite older.
//   - Packets older than `window_ms` are ignored at resolve time.
//
// Aggregator modes:
//   - kModeMeanLogits:        plain mean of int8 logits (research headline)
//   - kModeTemperatureScaled: mean of softmax(logits_k / T_k)  (calibrated)
//   - kModeLearnedWeights:    Σ w_k * logits_k                 (val-fitted)
//
// Calibration / weights live in `aggregator_params.h` (auto-generated by the
// training notebook). Header is included only when present, so the firmware
// still builds before the first ensemble run.

#ifndef HASH_KWS_ENSEMBLE_AGGREGATOR_H_
#define HASH_KWS_ENSEMBLE_AGGREGATOR_H_

#include <stddef.h>
#include <stdint.h>

#ifndef HASH_KWS_AGG_MAX_NODES
#define HASH_KWS_AGG_MAX_NODES 4
#endif

#ifndef HASH_KWS_AGG_MAX_CLASSES
#define HASH_KWS_AGG_MAX_CLASSES 12
#endif

namespace hash_kws_ensemble {

enum class Mode : uint8_t {
  kModeMeanLogits = 0,
  kModeTemperatureScaled = 1,
  kModeLearnedWeights = 2,
};

enum class SourceKind : uint8_t {
  kInfer = 0,
  kEpisode = 1,
  kEmit = 2,  // highest priority — overrides earlier infer/episode in same window
};

struct Vote {
  uint8_t  node_id;
  uint8_t  has_data;
  SourceKind source;
  uint32_t device_time_ms;
  uint32_t host_arrival_ms;
  int8_t   logits[HASH_KWS_AGG_MAX_CLASSES];
};

struct Resolved {
  uint8_t  has_decision;
  uint8_t  num_voters;
  uint8_t  label;
  int16_t  score;       // top1 from aggregated logits, scaled by 256 (Q8.8)
  int16_t  margin;      // top1 - top2, same scaling
  Mode     mode_used;
  uint32_t window_anchor_ms;
};

class Aggregator {
 public:
  void reset(uint8_t num_nodes, uint8_t num_classes, uint32_t window_ms);

  // Optional: install per-model temperatures (length == num_nodes).
  // If never called, mode kModeTemperatureScaled falls back to kModeMeanLogits.
  void setTemperatures(const float* temperatures);

  // Optional: install learned weights (length == num_nodes, will be normalized).
  // If never called, mode kModeLearnedWeights falls back to kModeMeanLogits.
  void setLearnedWeights(const float* weights);

  void setMode(Mode mode) { mode_ = mode; }
  Mode mode() const { return mode_; }

  // Minimum number of voters within window required to emit a decision.
  // Default 2. Set to 1 to allow single-node debugging; 3 for strict mode.
  void setMinVoters(uint8_t min_voters) {
    min_voters_ = (min_voters == 0) ? 1 : min_voters;
  }
  uint8_t minVoters() const { return min_voters_; }

  // Bitmask of class indices that the aggregator must never pick as top1
  // (or top2 when computing margin). Bit `i` set ⇒ class `i` is "noise".
  // Default 0 (no masking). Typically used to drop "unknown" / "silence"
  // from the KWS label set so the fusion never elects a noise label.
  // The masked classes are still included in the mean_logits computation,
  // only their selection at the top is suppressed.
  void setNoiseMask(uint16_t noise_mask) { noise_mask_ = noise_mask; }
  uint16_t noiseMask() const { return noise_mask_; }

  // Insert a vote. node_id is 1-based to match firmware conventions.
  // logits is a length-num_classes int8 vector. Returns false if rejected.
  bool submit(uint8_t node_id, SourceKind source,
              uint32_t device_time_ms, uint32_t host_arrival_ms,
              const int8_t* logits, uint8_t num_classes);

  // Resolve any decision over the most recent window. Returns has_decision=1
  // only if at least 2 nodes have data within the window.
  void resolve(uint32_t now_ms, Resolved* out) const;

  uint8_t numNodes() const { return num_nodes_; }
  uint8_t numClasses() const { return num_classes_; }
  uint32_t windowMs() const { return window_ms_; }

 private:
  uint8_t num_nodes_ = 0;
  uint8_t num_classes_ = 0;
  uint32_t window_ms_ = 1200;
  Mode mode_ = Mode::kModeMeanLogits;
  bool have_temperatures_ = false;
  bool have_learned_weights_ = false;
  uint8_t min_voters_ = 2;
  uint16_t noise_mask_ = 0;
  float temperatures_[HASH_KWS_AGG_MAX_NODES] = {0};
  float learned_weights_[HASH_KWS_AGG_MAX_NODES] = {0};
  Vote votes_[HASH_KWS_AGG_MAX_NODES] = {};
};

}  // namespace hash_kws_ensemble

#endif  // HASH_KWS_ENSEMBLE_AGGREGATOR_H_
