// vww_model_data.h
//
// Declarations for the flatbuffer-encoded TFLite VWW model.
// The implementation file (vww_model_data.cc) is GENERATED by
// code/training/image_classifier/export_vww_tflite.py and overwrites itself
// on each export. Do not hand-edit vww_model_data.cc.

#pragma once

#include <cstddef>
#include <cstdint>

extern const unsigned char vww_model_data[];
extern const unsigned int  vww_model_data_len;
