// Auto-generated by code/training/hash_ensemble notebook.
// One temperature per model + softmax-normalized 3-weight ensemble head.
// Both fitted on validation split only — test metrics are not leaked.
// Models order: ens_a, ens_b, ens_c

#ifndef HASH_KWS_AGGREGATOR_PARAMS_H_
#define HASH_KWS_AGGREGATOR_PARAMS_H_

#include <stddef.h>

static const size_t kHashEnsembleNumModels = 3;
static const size_t kHashEnsembleNumClasses = 12;

static const float kHashEnsembleTemperatures[kHashEnsembleNumModels] = {
0.83955264f, 0.84006238f, 0.86000583f
};

static const float kHashEnsembleLearnedWeights[kHashEnsembleNumModels] = {
0.33336884f, 0.33314513f, 0.33348604f
};

#endif  // HASH_KWS_AGGREGATOR_PARAMS_H_
